### ISSUE TITLE
specified material (None)  not loaded!

### ISSUE THREAD

**Issue by whu-lee** [ajhamdi/MVTN#1]
Thank you very much for your paper and code, but this problem appeared when I ran the code. Could you tell me how to solve it? thank you very much.
![image](https://user-images.githubusercontent.com/69310975/132987740-88240746-4dff-4ba8-876b-2da3b0f23b03.png)

**Comment by whu-lee** [comment]
![image](https://user-images.githubusercontent.com/69310975/132987873-f2450e9d-715a-4280-b2d7-d1e8b14251d0.png)

**Comment by ajhamdi** [comment]
@whu-lee  what dataset is this ?

**Comment by whu-lee** [comment]
Thank you very much for your reply.
The dataset is modelnet40.
I just set “num_workers=0”.

**Comment by ajhamdi** [comment]
@whu-lee 
for the number of workers, it would be preferred to be <=4. 

For the Warnings about not available materials, We are not using the material of the objects in this project, so you can ignore it or shut it down with the following code 

```python
import logging
logger = logging.getLogger("trimesh")
logger.setLevel(logging.ERROR)
```
