### ISSUE TITLE
I can't get the accuracy in the paper

### ISSUE THREAD

**Issue by liuyuanqing** [ajhamdi/MVTN#13]
In paper,MVTN using resnet18 can get the accuracy of 90% on ModelNet40 test. I can only get 78% accuracy.My command is 
python run_mvtn.py --data_dir data/ModelNet40/ --run_mode train --mvnetwork mvcnn --nb_views 8 --views_config learned_spherical

**Comment by auniquesun** [comment]
> In paper,MVTN using resnet18 can get the accuracy of 90% on ModelNet40 test. I can only get 78% accuracy.My command is python run_mvtn.py --data_dir data/ModelNet40/ --run_mode train --mvnetwork mvcnn --nb_views 8 --views_config learned_spherical

Have you reproduce the results reported in this paper?

**Comment by LinyeLi60** [comment]
Why close this issue, I also cannot reproduce the results.
