### ISSUE TITLE
Remedy did not work

### ISSUE THREAD

**Issue by JerkyT** [ajhamdi/MVTN#14]
Hellow，Thanks for your nice work，there is a bug：

i did not change any parameters ，and run ：
```
CUDA_VISIBLE_DEVICES='2' python run_mvtn.py \
        --data_dir data/ModelNet40/ \
        --run_mode train \
        --mvnetwork mvcnn \
        --nb_views 8 \
        --views_config learned_spherical
```
output：
```
...
Evaluation:
        train acc: 82.79 - train Loss: 0.6117
        Val Acc: 76.54 - val Loss: 0.8504
        Current best val acc: 76.90

-----------------------------------
Epoch: [45/100]
        Iter [50/492] Loss: 0.4384
Remedy did not work
```

**Comment by ajhamdi** [comment]
hi @JerkyT this problem can happen if the views learned are at singularity 90 degrees which can cause a problem in the rotation matrix used by the renderer. Please try to increase the `EXAHSTION_LIMIT=20` in `ops.py` to `EXAHSTION_LIMIT=100` to reduce the chance of this error happening
