### ISSUE TITLE
shapenet_split.csv is missing

### ISSUE THREAD

**Issue by amiltonwong** [ajhamdi/MVTN#16]
Hi, @ajhamdi ,

When I run the experiment on ShapeNet dataset, a file called [shapenet_split.csv](https://github.com/ajhamdi/MVTN/blob/master/custom_dataset.py#L328) is required. However, I couldn't find it from the ShapeNet website, only a file called `all.csv` is found, which is used for `Training, validation and test splits for SHREC16 and SHREC17`. Is this `all.csv` I should use? If not, could you release the required `shapenet_split.csv` file?

Thanks

**Comment by ajhamdi** [comment]
yes , just rename it , sorry for late reply
