### ISSUE TITLE
How to find nb_points for custom dataset?

### ISSUE THREAD

**Issue by wlcosta** [ajhamdi/MVTN#6]
Hey! I am new to this kind of approach and wanted to apply it to a custom dataset of mine. How do I find the correct `nb_points` value for my dataset? Thanks!

**Comment by ajhamdi** [comment]
Hi @wlcosta . You don't find that number, you basically pass it to your data loader which in turns sample as many points as desired. You have to create your own data loader. See [custom_datasets.py](https://github.com/ajhamdi/MVTN/blob/master/custom_dataset.py) for examples.
