### ISSUE TITLE
Input points for Classification (1k or 2k) ?

### ISSUE THREAD

**Issue by sheshap** [ajhamdi/MVTN#7]
Can you please confirm if the classification results are using 2048 input points instead of 1024 points?

Not clear from the tables (mainly because results of previous models are based on 1024 input points). 

Kindly share the results of classification with 1024 points or provide exact commands and configurations to recreate the results.

Thanks in advance

**Comment by ajhamdi** [comment]
@sheshap 
for the ModelNet40 datasets , please use mesh rendering ( not point cloud rendering, as detailed in the paper) 
for the scanobjectNN dataset, the default is 2048 points. Please check the paper for more details
